[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Sumrid Klinkanha <59070174@it.kmitl.ac.th>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1.2"
